Endpoint validation
RedHatInsights/sources-api-go pull request #43
Opened 2021-10-27 10:22 UTC by MikelAlejoBR

Implements the equivalent endpoint validation of [sources-api/app/models/endpoint.rb](https://github.com/RedHatInsights/sources-api/blob/master/app/models/endpoint.rb) plus some extra validations. The validations that have been implemented are the following ones:

## Validations and defaults
- `SourceID`
    - Required, non-zero and positive number.
- `Default`
    - An endpoint can't be set as "default" if there's another endpoint for the given source marked as "default".
    - Marked as default if there aren't any other endpoints for the given source.
- `Role`
    - There must not exist another endpoint for the given source with the same role name.
- `Scheme`
    - Not required.
    - If it is `nil`, or it is not a valid scheme, it defaults to `https`
-  `Host`
    - Not required.
    - Can't be longer than 255 chars (RFC2181). Can't have labels longer than 63 chars (RFC2181).
    - Must be a valid host (RFC1034 and RFC2181)
- `Port`
    - Not required. If provided, must be lower than MAXPORT.
    - Defaults to `443`
- `VerifySsl`
    - Not required.
    - Defaults to `true`
- `CertificateAuthority`
    - Not required.
    - Must not be null if `VerifySsl` is set as `true`.
- `AvailabilityStatus`
    - Required.
    - Must be one of `("", "available", "unavailable")`.

[[RHCLOUD-16766]](https://issues.redhat.com/browse/RHCLOUD-16766)

2021-10-27 12:14 UTC, MikelAlejoBR commented
@lindgrenj6, I was thinking on leaving this PR as-is instead of adding more stuff to it —spec, routes and handler code—, because I have the feeling that this is already pretty big. What do you think?

Also, another note: does it make sense to have the `AvailabilityStatusError` member on `*Create` models? Because I understand that it makes sense to have it when querying for the object itself, to know why my endpoint or source is unavailable... But on creation?

2021-10-27 16:50 UTC, lindgrenj6 requested changes
Just a few comments - I know the spec was probably your source but unfortunately its wrong. The model has most of the behavior (or lack thereof). 

Also I'm ok with a followup PR on the actual handlers - this PR is pretty large already.

2021-10-27 16:50 UTC, lindgrenj6 commented on dao/endpoint_dao.go
> +	result := DB.Where("\"default\" = true AND source_id = ?", sourceId).First(&endpoint)
small nit (and it's taking me forever to type this because github markdown overtakes it): 
You can use [string literals](https://golang.org/ref/spec#String_literals) so that you don't have to escape the quotes. Basically just use backticks intstead of quotes.

2021-10-27 16:50 UTC, lindgrenj6 commented on model/endpoint_http.go
> +	AvailabilityStatusError string  `json:"availability_status_error"`
correct - this field doesn't quite make sense for a create request. I know it was in the spec, but the spec was generated...and generated incorrectly!

2021-10-27 16:50 UTC, lindgrenj6 commented on model/endpoint_http.go
> +	SourceID                *string `json:"source_id"`
For this field we might want to use the same logic and helper methods we have in the Source creation workflow so we can accept integers AND strings for the foreign key reference.

2021-10-27 16:50 UTC, lindgrenj6 commented on service/endpoint_validation.go
> +	sourceId, err := util.InterfaceToInt64(ecr.SourceID)
Ok sweet - just need to change the field to `interface{}` in the create request and do the same `*Raw` pattern.

2021-10-27 16:50 UTC, lindgrenj6 commented on service/endpoint_validation.go
> +	if ecr.Default == nil {
On the rails side we are defaulting to true if it isn't present, here: https://github.com/RedHatInsights/sources-api/blob/dca0a0fd9d829e2765389aa418348b99719948b8/app/models/endpoint.rb#L16

It looks like you're already checking for multiple defaults and setting to true if not - so we just need to make sure this field isn't required on create. If the spec said it was required its probably wrong for create requests - its just always there on response because we set a default.

2021-10-27 16:50 UTC, lindgrenj6 commented on service/endpoint_validation.go
> +	}
Receptor node is not required - spec is probably wrong for create requests.

2021-10-27 16:50 UTC, lindgrenj6 commented on service/endpoint_validation.go
> +	}
role actually can be empty - empty role is default, but uniqueness per tenant is still enforced.

2021-10-27 16:50 UTC, lindgrenj6 commented on service/endpoint_validation.go
> +	}
host actually can be empty too (for sources where they're just connecting via a receptor node they won't have host present).

2021-10-28 07:52 UTC, MikelAlejoBR commented on dao/endpoint_dao.go
> +	result := DB.Where("\"default\" = true AND source_id = ?", sourceId).First(&endpoint)
Got it, thanks!

2021-10-28 08:09 UTC, MikelAlejoBR commented on model/endpoint_http.go
> +	AvailabilityStatusError string  `json:"availability_status_error"`
Great! Removing...

2021-10-28 09:18 UTC, MikelAlejoBR commented on model/endpoint_http.go
> +	SourceID                *string `json:"source_id"`
All right, doing it now.

2021-10-28 09:28 UTC, MikelAlejoBR commented on service/endpoint_validation.go
> +	}
All right, now is set as optional.

2021-10-28 09:35 UTC, MikelAlejoBR commented on service/endpoint_validation.go
> +	}
My bad. I actually thought it was weird to validate for uniqueness when we're accepting empty strings, so I made the change to actually not accept them. Now it accepts empty strings and checks for uniqueness!

2021-10-28 09:48 UTC, MikelAlejoBR commented on service/endpoint_validation.go
> +	}
Got it, now we accept empty hosts, and validations only take place when receiving a non-empty one.

2021-10-28 09:59 UTC, MikelAlejoBR commented on service/endpoint_validation.go
> +	if ecr.Default == nil {
All right, removed that "required" constraint.

2021-10-28 10:03 UTC, MikelAlejoBR commented
Thanks for the review @lindgrenj6. I've implemented all the requested changes :+1:

2021-10-28 19:57 UTC, lindgrenj6 approved these changes
Looks great!

2021-10-28 19:57 UTC, merged