[RHCLOUD-20616] add check if ENCRYPTION_KEY is not set into InitializeEncryption
RedHatInsights/sources-api-go pull request #564
Opened 2022-09-14 19:31 UTC by Ellen-Yi-Dong

Added check for situation when ENCRYPTION_KEY is not set in InitializeEncryption()

if ENCRYPTION_KEY is empty, then send a panic error 

LINK: [RHCLOUD-20616](https://issues.redhat.com/browse/RHCLOUD-20616)

2022-09-16 08:28 UTC, lpichler commented
yes, this will save a time!

2022-09-19 10:55 UTC, petracihalova requested changes

2022-09-19 10:55 UTC, petracihalova commented on util/encryption.go
> +	}
I believe this is not working as we need

if key is empty we set there some default value - but the value is set only into environment variables, the "key" variable stays empty 
+
maybe  we can use here some nice private function to set default value, something like
```
if key == "" {
    key = setDefaultEncryptionKey()
}
```

2022-09-26 07:49 UTC, MikelAlejoBR reviewed
I'm not sure about the use case for this one. I'm guessing this is for development purposes, so that we don't have to set an encryption key to make it work?

My feeling is that it might be better to simply let it panic as it did before, maybe with a more user friendly message. Just because:

1. We're setting a default encryption key which is public to everyone.
2. If we forget to set a proper encryption key on stage or prod —highly unlikely, I know—, I don't foresee myself in the future saying "oh, I need to check if the encryption key was properly set". Probably I would totally forget about it.

I'd like to hear everyone's views on this, please!

2022-09-26 07:49 UTC, MikelAlejoBR commented on util/encryption.go
> +}
In this case I'd suggest not ignoring the error, and returning early. If the `Setenv` function returns an error, you know for sure that the value you wanted wasn't set.

2022-10-11 18:48 UTC, Ellen-Yi-Dong commented
/retest

2022-10-12 14:31 UTC, lindgrenj6 reviewed
Great next pass! I think we're mostly there - we just need to let the user create the symlink rather than doing it for them.

2022-10-12 14:31 UTC, lindgrenj6 commented on util/encryption.go
> +	return nil
This else block can be removed since it's falling through if we're not on stage/prod - and the final return statement should probably be an error right? Since we want to panic and let the user know we couldn't set a default encryption key.

2022-10-12 14:31 UTC, lindgrenj6 commented on util/encryption.go
> +		}
~I'm not following this - can you explain why we do a runtime call to see where we're at in the program?~

This would be a good example where a comment would help in the future for reference - something like 

`// fetch the filename so we know where to get the source encryption_key.dev file from`

2022-10-12 14:31 UTC, lindgrenj6 commented on util/encryption.go
> +			os.Setenv("ENCRYPTION_KEY", string(body))
This is exactly right - the only thing I would suggest is also setting the package var `key` to `string(body)` too since we won't be calling this again (other than maybe in tests).

2022-10-12 14:31 UTC, lindgrenj6 commented on util/encryption.go
> +	if os.Getenv("SOURCES_ENV") != "stage" && os.Getenv("SOURCES_ENV") != "prod" {
Here you should be able to use `config.Get().Env` - we parse it at the beginning of the app startup.

2022-10-12 14:31 UTC, lindgrenj6 commented on util/encryption.go
> +
Ohhhhh I see why you needed it now. 

I should have maybe been more specific. We don't want to make the symlink for the user in code - we want to just return a nice error that says "hey you need to symlink `encryption_key.dev` to `encryption_key`". 

That way the user themselves have to run `ln -s ...` we could even put the command in the error message.

2023-02-08 20:23 UTC, petracihalova approved these changes
nice job

2024-08-06 20:25 UTC, lindgrenj6 commented
/retest

2024-08-06 21:43 UTC, lindgrenj6 commented
/retest

2024-08-07 17:56 UTC, Ellen-Yi-Dong commented
/retest

2024-08-07 21:16 UTC, Ellen-Yi-Dong commented
/retest

2024-08-07 23:53 UTC, merged