[WIP] Add Static Cache for Application/Source Type Id's
RedHatInsights/sources-api-go pull request #69
Opened 2022-01-10 20:03 UTC by lindgrenj6

This PR adds the static cache we discussed in Slack today. This is what it looks like in memory:
![image](https://user-images.githubusercontent.com/5856504/148831181-6d5cc180-011d-420b-8ca9-419851f3f10b.png)

---

I have comments in the struct but will add more here. Basically it caches the `SourceType` name -> id mapping as well as the `ApplicationType` name -> id mapping. For ApplicationType though I did not only the path-style name but also the "short" name since we use that in some places in the app.

---

I also have another commit as an example of it being used: limiting satellite listing sources to _only_ the satellite source_type_id.

\# TODO:
- [ ] Tests for SourceList with cert-auth being used
- [ ] Maybe tests for the typeCache?

2022-01-11 08:15 UTC, MikelAlejoBR approved these changes

2022-01-26 13:14 UTC, lpichler approved these changes

2022-01-26 13:53 UTC, lpichler commented
@lindgrenj6 as this add test to `dao` package, the package most likely needs main_test.go, for example:


```
package dao

import (
	"os"
	"testing"
)

func TestMain(t *testing.M) {
	// we need this to parse arguments otherwise there are not recognized which lead to error
	_ = parser.ParseFlags()

	os.Exit(t.Run())
}
```

2022-01-26 18:02 UTC, lpichler requested changes
@lindgrenj6 as this add test to dao package, the package most likely needs main_test.go, for example:
```go
package dao

import (
	"os"
	"testing"
)

func TestMain(t *testing.M) {
	// we need this to parse arguments otherwise there are not recognized which lead to error
	_ = parser.ParseFlags()

	os.Exit(t.Run())
}
```

2022-01-26 18:07 UTC, lindgrenj6 commented
@lpichler i swear i added it - must have gotten lost :grin: added either way!

2022-01-26 18:16 UTC, lpichler approved these changes

2022-01-26 18:17 UTC, merged