Use interface for Vault instance
RedHatInsights/sources-api-go pull request #77
Opened 2022-01-24 14:44 UTC by lpichler

This change also add mock struct which satisfy interface `LogicalClient` as well as `vault.Logical` - it can be used for testing for Vault-related code.

### Links
Pull out from https://github.com/RedHatInsights/sources-api-go/pull/76

2022-01-24 21:13 UTC, lindgrenj6 requested changes

2022-01-24 21:13 UTC, lindgrenj6 commented on dao/authentication_dao.go
> +	out, err := (*Vault).Write(path, data)
So I'm actually kind of mad at myself that I missed this the first time in the availability status listener pr :disappointed:. 

We shouldn't be using pointers of interfaces because basically an interface is a pointer to a struct that satisfies a "signature", so basically an interface type is _already_ a pointer.

For example see here how I instantiated an Rbac interface var: https://github.com/RedHatInsights/sources-api-go/blob/e5ad9bbed6af58bf92fb9540cefebac7fd42069c/middleware/authorization.go#L20

The Interface var is assigned a pointer to a struct that "satisfies" the interface. 

I noticed it last time and thought a bit about it here: https://github.com/RedHatInsights/sources-api-go/blob/e5ad9bbed6af58bf92fb9540cefebac7fd42069c/dao/common.go#L9 I didn't notice that the `EventModelDao` is actually an interface - therefore we shouldn't be returning pointers to it. Basically a pointer to an interface makes it take double de-referencing which doubles the potential for null-pointer errors. This way we won't have to de-ref the pointer before calling methods on the structs as well. 

also: you can see here https://github.com/RedHatInsights/sources-api-go/blob/e5ad9bbed6af58bf92fb9540cefebac7fd42069c/dao/common.go#L13

that basically we're returning a pointer to a pointer. Should have jumped out to me more but I glossed over it the first time.

---

tl; dr: can we refactor these functions/where they're used to not be pointers to interfaces. Everywhere there is `*EventModelDao` needs to just be `EventModelDao`. 

If this doesn't make sense let me know and I can try and explain it better in person, also if you don't want do do the `EventModelDao` changes in this PR thats fine - we can do them in a follow-up.

2022-01-24 21:13 UTC, lindgrenj6 commented on dao/db.go
> +	Vault       *LogicalClient
This is an interface so shouldn't be a pointer like I said earlier - this is what made me realize I missed it last time.

2022-01-24 21:13 UTC, lindgrenj6 commented on dao/db.go
> +	SetVault(vaultClient.Logical())
I actually don't think we need the function here - one can just do:
```go
Vault = &vaultClient.Logical()
````
and in tests, just overwrite it in the same way.

2022-01-24 21:13 UTC, lindgrenj6 commented on dao/interfaces.go
> +type LogicalClient interface {
Lets rename this to `VaultClient`.

2022-01-25 08:34 UTC, MikelAlejoBR approved these changes

2022-01-25 08:52 UTC, lpichler commented on dao/authentication_dao.go
> +	out, err := (*Vault).Write(path, data)
oh wow that's interesting - it definitely needs to be changed.

Regard to:
https://github.com/RedHatInsights/sources-api-go/blob/e5ad9bbed6af58bf92fb9540cefebac7fd42069c/dao/common.go#L13

It looks same like this 

https://github.com/RedHatInsights/sources-api-go/blob/e5ad9bbed6af58bf92fb9540cefebac7fd42069c/middleware/authorization.go#L20

I would say it is initialising pointer with address(`&SourceDaoImpl{}`) which seems correct  as `resource` is not pointer on interface(correct me if I am wrong) but definitely returning values needs to be changed  in the functions and also other occurrence.

I will change `*EventModelDao` in follow up PR and I prefer to do it after series of PRs about adding auths and appauths to listener.

@lindgrenj6 It does make sense and thanks for explanation!

2022-01-25 08:53 UTC, lpichler commented on dao/db.go
> +	SetVault(vaultClient.Logical())
when `Vault` is interface variable then just
`Vault = vaultClient.Logical()`

2022-01-25 08:56 UTC, lpichler commented
thanks @MikelAlejoBR for review 👍 

and @lindgrenj6 I updated PR according to your suggestions and now it is very little change

2022-01-25 13:49 UTC, lindgrenj6 commented on dao/authentication_dao.go
> +	out, err := (*Vault).Write(path, data)
Yep that sounds good to me. Just the return type being a pointer is the part I had missed last time - it's easy to add many layers of indirection!

2022-01-25 14:09 UTC, lindgrenj6 approved these changes

2022-01-25 14:09 UTC, merged